### ISSUE TITLE
Installation failed

### ISSUE THREAD

**Issue by Rush** [ddopson/node-segfault-handler#13]
openSUSE 13.1, G++ 4.8, node.js 0.11
```
npm install git://github.com/ddopson/node-segfault-handler.git --nodedir=/home/rush/Programowanie/node
npm WARN package.json http-proxy@1.0.1 No repository field.
npm http GET https://registry.npmjs.org/bindings
npm http 304 https://registry.npmjs.org/bindings

> segfault-handler@0.2.1 install /home/rush/Programowanie/http-master/node_modules/segfault-handler
> node-gyp rebuild

make: Entering directory `/home/rush/Programowanie/http-master/node_modules/segfault-handler/build'
  CXX(target) Release/obj.target/segfault_handler/src/segfault-handler.o
In file included from /home/rush/Programowanie/node/src/node.h:61:0,
                 from ../src/segfault-handler.cpp:11:
/home/rush/Programowanie/node/deps/v8/include/v8.h: In member function 'void v8::ReturnValue<T>::Set(uint32_t)':
/home/rush/Programowanie/node/deps/v8/include/v8.h:5816:31: warning: typedef 'I' locally defined but not used [-Wunused-local-typedefs]
   typedef internal::Internals I;
                               ^
../src/segfault-handler.cpp: At global scope:
../src/segfault-handler.cpp:21:39: error: 'siginfo_t' has not been declared
 static void segfault_handler(int sig, siginfo_t *si, void *unused) {
                                       ^
../src/segfault-handler.cpp: In function 'void segfault_handler(int, int*, void*)':
../src/segfault-handler.cpp:38:102: error: request for member 'si_addr' in '* si', which is of non-class type 'int'
   n = snprintf(sbuff, sizeof(sbuff), "PID %d received SIGSEGV for address: 0x%lx\n", pid, (long) si->si_addr);
                                                                                                      ^
../src/segfault-handler.cpp: At global scope:
../src/segfault-handler.cpp:75:35: error: 'Arguments' does not name a type
 Handle<Value> CauseSegfault(const Arguments& args) {
                                   ^
../src/segfault-handler.cpp:75:46: error: ISO C++ forbids declaration of 'args' with no type [-fpermissive]
 Handle<Value> CauseSegfault(const Arguments& args) {
                                              ^
../src/segfault-handler.cpp:82:37: error: 'Arguments' does not name a type
 Handle<Value> RegisterHandler(const Arguments& args) {
                                     ^
../src/segfault-handler.cpp:82:48: error: ISO C++ forbids declaration of 'args' with no type [-fpermissive]
 Handle<Value> RegisterHandler(const Arguments& args) {
                                                ^
../src/segfault-handler.cpp: In function 'v8::Handle<v8::Value> RegisterHandler(const int&)':
../src/segfault-handler.cpp:83:20: error: aggregate 'RegisterHandler(const int&)::sigaction sa' has incomplete type and cannot be defined
   struct sigaction sa;
                    ^
../src/segfault-handler.cpp:84:41: error: invalid application of 'sizeof' to incomplete type 'RegisterHandler(const int&)::sigaction'
   memset(&sa, 0, sizeof(struct sigaction));
                                         ^
../src/segfault-handler.cpp:85:26: error: 'sigemptyset' was not declared in this scope
   sigemptyset(&sa.sa_mask);
                          ^
../src/segfault-handler.cpp:87:19: error: 'SA_SIGINFO' was not declared in this scope
   sa.sa_flags   = SA_SIGINFO;
                   ^
../src/segfault-handler.cpp:88:13: error: 'SIGSEGV' was not declared in this scope
   sigaction(SIGSEGV, &sa, NULL);
             ^
../src/segfault-handler.cpp:88:31: error: invalid use of incomplete type 'struct RegisterHandler(const int&)::sigaction'
   sigaction(SIGSEGV, &sa, NULL);
                               ^
../src/segfault-handler.cpp:83:10: error: forward declaration of 'struct RegisterHandler(const int&)::sigaction'
   struct sigaction sa;
          ^
../src/segfault-handler.cpp: In function 'void init(v8::Handle<v8::Object>)':
../src/segfault-handler.cpp:94:63: error: no matching function for call to 'NODE_SET_METHOD(v8::Handle<v8::Object>&, const char [16], v8::Handle<v8::Value> (&)(const int&))'
     NODE_SET_METHOD(target, "registerHandler", RegisterHandler);
                                                               ^
../src/segfault-handler.cpp:94:63: note: candidate is:
In file included from ../src/segfault-handler.cpp:11:0:
/home/rush/Programowanie/node/src/node.h:191:13: note: template<class TypeName> void node::NODE_SET_METHOD(const TypeName&, const char*, v8::FunctionCallback)
 inline void NODE_SET_METHOD(const TypeName& recv,
             ^
/home/rush/Programowanie/node/src/node.h:191:13: note:   template argument deduction/substitution failed:
../src/segfault-handler.cpp:94:63: note:   cannot convert 'RegisterHandler' (type 'v8::Handle<v8::Value>(const int&)') to type 'v8::FunctionCallback {aka void (*)(const v8::FunctionCallbackInfo<v8::Value>&)}'
     NODE_SET_METHOD(target, "registerHandler", RegisterHandler);
                                                               ^
../src/segfault-handler.cpp:95:59: error: no matching function for call to 'NODE_SET_METHOD(v8::Handle<v8::Object>&, const char [14], v8::Handle<v8::Value> (&)(const int&))'
     NODE_SET_METHOD(target, "causeSegfault", CauseSegfault);
                                                           ^
../src/segfault-handler.cpp:95:59: note: candidate is:
In file included from ../src/segfault-handler.cpp:11:0:
/home/rush/Programowanie/node/src/node.h:191:13: note: template<class TypeName> void node::NODE_SET_METHOD(const TypeName&, const char*, v8::FunctionCallback)
 inline void NODE_SET_METHOD(const TypeName& recv,
             ^
/home/rush/Programowanie/node/src/node.h:191:13: note:   template argument deduction/substitution failed:
../src/segfault-handler.cpp:95:59: note:   cannot convert 'CauseSegfault' (type 'v8::Handle<v8::Value>(const int&)') to type 'v8::FunctionCallback {aka void (*)(const v8::FunctionCallbackInfo<v8::Value>&)}'
     NODE_SET_METHOD(target, "causeSegfault", CauseSegfault);
                                                           ^
make: *** [Release/obj.target/segfault_handler/src/segfault-handler.o] Error 1
make: Leaving directory `/home/rush/Programowanie/http-master/node_modules/segfault-handler/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:267:23)
gyp ERR! stack     at ChildProcess.EventEmitter.emit (events.js:107:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1036:12)
gyp ERR! System Linux 3.11.10-7-desktop
gyp ERR! command "node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/rush/Programowanie/http-master/node_modules/segfault-handler
gyp ERR! node -v v0.11.12-pre
gyp ERR! node-gyp -v v0.12.2
gyp ERR! not ok 
npm ERR! segfault-handler@0.2.1 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the segfault-handler@0.2.1 install script.
npm ERR! This is most likely a problem with the segfault-handler package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls segfault-handler
npm ERR! There is likely additional logging output above.

npm ERR! System Linux 3.11.10-7-desktop
npm ERR! command "/usr/local/bin/node" "/usr/local/bin/npm" "install" "git://github.com/ddopson/node-segfault-handler.git" "--nodedir=/home/rush/Programowanie/node"
npm ERR! cwd /home/rush/Programowanie/http-master
npm ERR! node -v v0.11.12-pre
npm ERR! npm -v 1.4.3
npm ERR! code ELIFECYCLE
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /home/rush/Programowanie/http-master/npm-debug.log
npm ERR! not ok code 0
```

**Comment by No9** [comment]
ok so Nan has been in for a while now and so I am closing this one.
