### ISSUE TITLE
installation error osx

### ISSUE THREAD

**Issue by RamonDonnell** [ddopson/node-segfault-handler#29]
````
>sw_vers
ProductName:	Mac OS X
ProductVersion:	10.10.5
BuildVersion:	14F27
>node -v
v4.0.0
>npm -v
2.14.2
> npm install segfault-handler

npm WARN package.json @ No description
npm WARN package.json @ No repository field.
npm WARN package.json @ No README data
npm WARN package.json @ No license field.
\
> segfault-handler@0.2.4 install /devel/source/xxxxx/apps/services/test/api/node_modules/segfault-handler
> node-gyp rebuild

gyp: /Users/xxxxx/.node-gyp/4.0.0/common.gypi not found (cwd: /devel/source/xxxxx/apps/services/test/api/node_modules/segfault-handler) while reading includes of binding.gyp while trying to load binding.gyp
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/local/Cellar/nvm/0.26.1/versions/node/v4.0.0/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:357:16)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Darwin 14.5.0
gyp ERR! command "/usr/local/Cellar/nvm/0.26.1/versions/node/v4.0.0/bin/node" "/usr/local/Cellar/nvm/0.26.1/versions/node/v4.0.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /devel/source/xxxxx/apps/services/test/api/node_modules/segfault-handler
gyp ERR! node -v v4.0.0
gyp ERR! node-gyp -v v2.0.2
gyp ERR! not ok
npm ERR! Darwin 14.5.0
npm ERR! argv "/usr/local/Cellar/nvm/0.26.1/versions/node/v4.0.0/bin/node" "/usr/local/opt/nvm/versions/node/v4.0.0/bin/npm" "install" "segfault-handler"
npm ERR! node v4.0.0
npm ERR! npm  v2.14.2
npm ERR! code ELIFECYCLE

npm ERR! segfault-handler@0.2.4 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the segfault-handler@0.2.4 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the segfault-handler package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls segfault-handler
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /devel/source/xxxxxx/apps/services/test/api/npm-debug.log
````

poking around ~/.node-gyp/4.0.0/common.gypi is now  ~/.node-gyp/4.0.0/include/node/common.gypi

**Comment by No9** [comment]
Hi @RamonDonnell 
We don't have any additional functionality over the standard gyp implementation.
i.e. we don't specify `~/.node-gyp/4.0.0/common.gypi` in our build scripts anywhere
So this looks like gyp issue. 
I know node-gyp was bumped to 3.0.1 yesterday for 4.0.0 and you appear to be using `node-gyp -v v2.0.2` 
Can you update to latest node-gyp and try again please.

**Comment by RamonDonnell** [comment]
should've picked that up. Upped to 3.0.1, this solved my original segfault issue, so don't need segfault-handler anymore. 
Tried to install anyway, gives the following.
````

npm WARN package.json xxxxpartner@0.0.1 No license field.
/
> segfault-handler@0.2.4 install /devel/source/xxxx/apps/node_modules/segfault-handler
> node-gyp rebuild

xcode-select: error: tool 'xcodebuild' requires Xcode, but active developer directory '/Library/Developer/CommandLineTools' is a command line tools instance

xcode-select: error: tool 'xcodebuild' requires Xcode, but active developer directory '/Library/Developer/CommandLineTools' is a command line tools instance

CXX(target) Release/obj.target/segfault-handler/src/segfault-handler.o
In file included from ../src/segfault-handler.cpp:16:
../node_modules/nan/nan.h:324:27: error: redefinition of 'NanEnsureHandleOrPersistent'
NAN_INLINE v8::Local<T> NanEnsureHandleOrPersistent(const v8::Local<T> &val) {
^
../node_modules/nan/nan.h:319:17: note: previous definition is here
	v8::Handle<T> NanEnsureHandleOrPersistent(const v8::Handle<T> &val) {
	^
	../node_modules/nan/nan.h:344:27: error: redefinition of 'NanEnsureLocal'
		NAN_INLINE v8::Local<T> NanEnsureLocal(const v8::Handle<T> &val) {
		^
		../node_modules/nan/nan.h:334:27: note: previous definition is here
			NAN_INLINE v8::Local<T> NanEnsureLocal(const v8::Local<T> &val) {
			^
			../node_modules/nan/nan.h:757:13: error: no member named 'smalloc' in namespace 'node'
					, node::smalloc::FreeCallback callback
				~~~~~~^
			../node_modules/nan/nan.h:768:12: error: no matching function for call to 'New'
				return node::Buffer::New(v8::Isolate::GetCurrent(), data, size);
			^~~~~~~~~~~~~~~~~
					/Users/xxxx/.node-gyp/4.0.0/include/node/node_buffer.h:31:40: note: candidate function not viable: no known conversion from 'uint32_t' (aka 'unsigned int') to 'enum encoding' for 3rd argument
				NODE_EXTERN v8::MaybeLocal<v8::Object> New(v8::Isolate* isolate,
			^
				/Users/xxxx/.node-gyp/4.0.0/include/node/node_buffer.h:43:40: note: candidate function not viable: 2nd argument ('const char *') would lose const qualifier
				NODE_EXTERN v8::MaybeLocal<v8::Object> New(v8::Isolate* isolate,
			^
				/Users/xxxx/.node-gyp/4.0.0/include/node/node_buffer.h:28:40: note: candidate function not viable: requires 2 arguments, but 3 were provided
				NODE_EXTERN v8::MaybeLocal<v8::Object> New(v8::Isolate* isolate, size_t length);
			^
				/Users/xxxx/.node-gyp/4.0.0/include/node/node_buffer.h:36:40: note: candidate function not viable: requires 5 arguments, but 3 were provided
				NODE_EXTERN v8::MaybeLocal<v8::Object> New(v8::Isolate* isolate,
			^
				In file included from ../src/segfault-handler.cpp:16:
			../node_modules/nan/nan.h:772:12: error: no viable conversion from 'v8::MaybeLocal<v8::Object>' to 'v8::Local<v8::Object>'
				return node::Buffer::New(v8::Isolate::GetCurrent(), size);
			^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
					/Users/xxxx/.node-gyp/4.0.0/include/node/v8.h:210:7: note: candidate constructor (the implicit copy constructor) not viable: no known conversion from 'v8::MaybeLocal<v8::Object>' to 'const v8::Local<v8::Object> &' for 1st argument
				class Local {
				^
				/Users/xxxx/.node-gyp/4.0.0/include/node/v8.h:210:7: note: candidate constructor (the implicit move constructor) not viable: no known conversion from 'v8::MaybeLocal<v8::Object>' to 'v8::Local<v8::Object> &&' for 1st argument
						class Local {
				^
				/Users/xxxx/.node-gyp/4.0.0/include/node/v8.h:214:13: note: candidate template ignored: could not match 'Local' against 'MaybeLocal'
					V8_INLINE Local(Local<S> that)
				^
				/Users/xxxx/.node-gyp/4.0.0/include/node/v8.h:326:13: note: candidate template ignored: could not match 'S *' against 'v8::MaybeLocal<v8::Object>'
					V8_INLINE Local(S* that)
				^
					In file included from ../src/segfault-handler.cpp:16:
				../node_modules/nan/nan.h:779:26: error: no member named 'Use' in namespace 'node::Buffer'
						return node::Buffer::Use(v8::Isolate::GetCurrent(), data, size);
				~~~~~~~~~~~~~~^
					In file included from ../src/segfault-handler.cpp:11:
					In file included from /Users/xxxx/.node-gyp/4.0.0/include/node/node.h:42:
				/Users/xxxx/.node-gyp/4.0.0/include/node/v8.h:221:5: error: assigning to 'v8::Primitive *volatile' from incompatible type 'v8::Value *'
					TYPE_CHECK(T, S);
				^~~~~~~~~~~~~~~~
				/Users/xxxx/.node-gyp/4.0.0/include/node/v8.h:180:37: note: expanded from macro 'TYPE_CHECK'
						*(static_cast<T* volatile*>(0)) = static_cast<S*>(0);      \
				^ ~~~~~~~~~~~~~~~~~~
				../node_modules/nan/nan.h:501:12: note: in instantiation of function template specialization 'v8::Local<v8::Primitive>::Local<v8::Value>' requested here
						return NanEscapeScope(NanNew(v8::Undefined(v8::Isolate::GetCurrent())));
				^
				../node_modules/nan/nan.h:483:30: note: expanded from macro 'NanEscapeScope'
# define NanEscapeScope(val) scope.Escape(Nan::imp::NanEnsureLocal(val))
				^
					In file included from ../src/segfault-handler.cpp:11:
					In file included from /Users/xxxx/.node-gyp/4.0.0/include/node/node.h:42:
				/Users/xxxx/.node-gyp/4.0.0/include/node/v8.h:221:5: error: assigning to 'v8::Boolean *volatile' from incompatible type 'v8::Value *'
					TYPE_CHECK(T, S);
				^~~~~~~~~~~~~~~~
				/Users/xxxx/.node-gyp/4.0.0/include/node/v8.h:180:37: note: expanded from macro 'TYPE_CHECK'
						*(static_cast<T* volatile*>(0)) = static_cast<S*>(0);      \
				^ ~~~~~~~~~~~~~~~~~~
				../node_modules/nan/nan.h:511:12: note: in instantiation of function template specialization 'v8::Local<v8::Boolean>::Local<v8::Value>' requested here
						return NanEscapeScope(NanNew(v8::True(v8::Isolate::GetCurrent())));
				^
				../node_modules/nan/nan.h:483:30: note: expanded from macro 'NanEscapeScope'
# define NanEscapeScope(val) scope.Escape(Nan::imp::NanEnsureLocal(val))
				^
					In file included from ../src/segfault-handler.cpp:11:
					In file included from /Users/xxxx/.node-gyp/4.0.0/include/node/node.h:42:
				/Users/xxxx/.node-gyp/4.0.0/include/node/v8.h:221:5: error: assigning to 'v8::Function *volatile' from incompatible type 'v8::Value *'
					TYPE_CHECK(T, S);
				^~~~~~~~~~~~~~~~
				/Users/xxxx/.node-gyp/4.0.0/include/node/v8.h:180:37: note: expanded from macro 'TYPE_CHECK'
						*(static_cast<T* volatile*>(0)) = static_cast<S*>(0);      \
				^ ~~~~~~~~~~~~~~~~~~
				../node_modules/nan/nan.h:1645:12: note: in instantiation of function template specialization 'v8::Local<v8::Function>::Local<v8::Value>' requested here
						return NanEscapeScope(NanNew(handle)->Get(kCallbackIndex)
				^
				../node_modules/nan/nan.h:483:30: note: expanded from macro 'NanEscapeScope'
# define NanEscapeScope(val) scope.Escape(Nan::imp::NanEnsureLocal(val))
				^
					In file included from ../src/segfault-handler.cpp:11:
					In file included from /Users/xxxx/.node-gyp/4.0.0/include/node/node.h:42:
				/Users/xxxx/.node-gyp/4.0.0/include/node/v8.h:221:5: error: assigning to 'v8::Object *volatile' from incompatible type 'v8::Value *'
					TYPE_CHECK(T, S);
				^~~~~~~~~~~~~~~~
				/Users/xxxx/.node-gyp/4.0.0/include/node/v8.h:180:37: note: expanded from macro 'TYPE_CHECK'
						*(static_cast<T* volatile*>(0)) = static_cast<S*>(0);      \
				^ ~~~~~~~~~~~~~~~~~~
				../node_modules/nan/nan.h:1776:12: note: in instantiation of function template specialization 'v8::Local<v8::Object>::Local<v8::Value>' requested here
						return NanEscapeScope(
				^
				../node_modules/nan/nan.h:483:30: note: expanded from macro 'NanEscapeScope'
# define NanEscapeScope(val) scope.Escape(Nan::imp::NanEnsureLocal(val))
				^
						10 errors generated.
					make: *** [Release/obj.target/segfault-handler/src/segfault-handler.o] Error 1
					gyp ERR! build error
					gyp ERR! stack Error: `make` failed with exit code: 2
					gyp ERR! stack     at ChildProcess.onExit (/usr/local/Cellar/nvm/0.26.1/versions/node/v4.0.0/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:270:23)
					gyp ERR! stack     at emitTwo (events.js:87:13)
					gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
					gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
					gyp ERR! System Darwin 14.5.0
					gyp ERR! command "/usr/local/Cellar/nvm/0.26.1/versions/node/v4.0.0/bin/node" "/usr/local/Cellar/nvm/0.26.1/versions/node/v4.0.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
					gyp ERR! cwd /devel/source/xxxx/apps/node_modules/segfault-handler
					gyp ERR! node -v v4.0.0
					gyp ERR! node-gyp -v v3.0.1
					gyp ERR! not ok
					npm ERR! Darwin 14.5.0
					npm ERR! argv "/usr/local/Cellar/nvm/0.26.1/versions/node/v4.0.0/bin/node" "/usr/local/opt/nvm/versions/node/v4.0.0/bin/npm" "install" "segfault-handler"
					npm ERR! node v4.0.0
					npm ERR! npm  v2.14.2
					npm ERR! code ELIFECYCLE

					npm ERR! segfault-handler@0.2.4 install: `node-gyp rebuild`
					npm ERR! Exit status 1
					npm ERR!
					npm ERR! Failed at the segfault-handler@0.2.4 install script 'node-gyp rebuild'.
					npm ERR! This is most likely a problem with the segfault-handler package,
					npm ERR! not with npm itself.
					npm ERR! Tell the author that this fails on your system:
					npm ERR!     node-gyp rebuild
					npm ERR! You can get their info via:
					npm ERR!     npm owner ls segfault-handler
					npm ERR! There is likely additional logging output above.

					npm ERR! Please include the following file with any support request:
					npm ERR!     /devel/source/xxxx/apps/npm-debug.log
````

**Comment by No9** [comment]
So we get similar issues on linux 
I have bumped the version of nan and that fixes it on the platform
Can you verify buy cloning this repo and 'npm install' 
Thanks

**Comment by RamonDonnell** [comment]
no worries
````
> git clone git@github.com:ddopson/node-segfault-handler.git; cd node-segfault-handler
> npm install
npm WARN package.json segfault-handler@0.2.5 No repository field.
npm WARN package.json segfault-handler@0.2.5 No license field.
/
> segfault-handler@0.2.5 install /devel/source/node-segfault-handler
> node-gyp rebuild

xcode-select: error: tool 'xcodebuild' requires Xcode, but active developer directory '/Library/Developer/CommandLineTools' is a command line tools instance

xcode-select: error: tool 'xcodebuild' requires Xcode, but active developer directory '/Library/Developer/CommandLineTools' is a command line tools instance

  CXX(target) Release/obj.target/segfault-handler/src/segfault-handler.o
  SOLINK_MODULE(target) Release/segfault-handler.node
bindings@1.2.1 node_modules/bindings

nan@2.0.9 node_modules/nan
````

**Comment by No9** [comment]
@RamonDonnell did that build for you or is xcode configuration getting int the way?

**Comment by OmgImAlexis** [comment]
@No9 used `npm install ddopson/node-segfault-handler` and it works fine, trying from the old one on npm crashes because nan wasn't updated.

**Comment by No9** [comment]
Right hopefully @ddopson will add me to npm too so we can land this 
https://github.com/ddopson/node-segfault-handler/commit/62d9a7f0ab449cc4994dddf34e1ecbc5446e08cb

**Comment by No9** [comment]
Hey @RamonDonnell That pull mentioned above landed can we close this?
