### ISSUE TITLE
Installation issues on linux

### ISSUE THREAD

**Issue by davidmerfield** [ddopson/node-segfault-handler#40]
A quick search of this repo's issue history indicates there are others with similar problems.

node is version 4.4.2
npm is version 2.15.0
node-gyp is version 3.3.1

Full error message: 

```
> segfault-handler@1.0.0 install /var/www/Journal/node_modules/segfault-handler
> node-gyp rebuild

gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR
gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR
Traceback (most recent call last):
  File "/home/ec2-user/.nvm/v4.4.2/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py", line 16, in <module>
    sys.exit(gyp.script_main())
  File "/home/ec2-user/.nvm/v4.4.2/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/__init__.py", line 545, in script_main
    return main(sys.argv[1:])
  File "/home/ec2-user/.nvm/v4.4.2/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/__init__.py", line 538, in main
    return gyp_main(args)
  File "/home/ec2-user/.nvm/v4.4.2/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/__init__.py", line 514, in gyp_main
    options.duplicate_basename_check)
  File "/home/ec2-user/.nvm/v4.4.2/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/__init__.py", line 130, in Load
    params['parallel'], params['root_targets'])
  File "/home/ec2-user/.nvm/v4.4.2/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/input.py", line 2775, in Load
    variables, includes, depth, check, True)
  File "/home/ec2-user/.nvm/v4.4.2/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/input.py", line 391, in LoadTargetBuildFile
    includes, True, check)
  File "/home/ec2-user/.nvm/v4.4.2/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/input.py", line 243, in LoadOneBuildFile
    None)
  File "binding.gyp", line 1
    {
     ^
SyntaxError: invalid syntax
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/home/ec2-user/.nvm/v4.4.2/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:305:16)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Linux 3.14.44-32.39.amzn1.x86_64
gyp ERR! command "/home/ec2-user/.nvm/v4.4.2/bin/node" "/home/ec2-user/.nvm/v4.4.2/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /var/www/Journal/node_modules/segfault-handler
gyp ERR! node -v v4.4.2
gyp ERR! node-gyp -v v3.3.1
gyp ERR! not ok
npm ERR! Linux 3.14.44-32.39.amzn1.x86_64
npm ERR! argv "/home/ec2-user/.nvm/v4.4.2/bin/node" "/home/ec2-user/.nvm/v4.4.2/bin/npm" "install" "segfault-handler"
npm ERR! node v4.4.2
npm ERR! npm  v2.15.0
npm ERR! code ELIFECYCLE

npm ERR! segfault-handler@1.0.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the segfault-handler@1.0.0 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the segfault-handler package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs segfault-handler
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!
npm ERR!     npm owner ls segfault-handler
npm ERR! There is likely additional logging output above.
```

**Comment by johnfn** [comment]
Had the same problem. This is what fixed it:

`npm install https://github.com/ddopson/node-segfault-handler.git`

`cd node_modules/segfault-handler`

`node-gyp rebuild`

**Comment by alexlitty** [comment]
Still experiencing errors when running `npm install segfault` on node `v6.10.2` but it's moot; Installing from the repository directly, so they appear to be resolved.

I suppose the package just isn't up-to-date on npm.
