### ISSUE TITLE
node6 runtime error

### ISSUE THREAD

**Issue by lmeyerov** [ddopson/node-segfault-handler#41]
Getting the below error at runtime for the below use under node 6. Could not duplicate in an isolated test. Anyone seeing something similar?

Usage:
```
var SegfaultHandler = require('segfault-handler');
SegfaultHandler.registerHandler();
```

Runtime error:
```
"Error: Module did not self-register.
    at Error (native)
    at Object.Module._extensions..node (module.js:568:18)
    at Module.load (module.js:456:32)
    at tryModuleLoad (module.js:415:12)
    at Function.Module._load (module.js:407:3)
    at Module.require (module.js:466:17)
    at require (internal/module.js:20:19)
    at bindings (/Users/lmeyerov/Desktop/work4/viz-server/node_modules/graph-viz/node_modules/common/node_modules/segfault-handler/node_modules/bindings/bindings.js:76:44)
    at Object.<anonymous> (/Users/lmeyerov/Desktop/work4/viz-server/node_modules/graph-viz/node_modules/common/node_modules/segfault-handler/index.js:3:37)
```

**Comment by dresende** [comment]
I'm also having this problem. I'm searching for alternatives if this doesn't get solved 😢

**Comment by simison** [comment]
For now you could do something like this:

```javascript
if (process.version.indexOf('v4') === 0 || process.version.indexOf('v5') === 0) {
  var SegfaultHandler = require('segfault-handler');
  SegfaultHandler.registerHandler();
}
```

**Comment by dresende** [comment]
Yes, I'm requiring it inside a `try` block, but I would prefer it to work since I find it quite precious when my app just blows the house 😄

**Comment by doublerebel** [comment]
This module works for me on Node 6.9.1 .  Is this still a valid bug for you all?
