### ISSUE TITLE
will any even better stack dumping?

### ISSUE THREAD

**Issue by wanjochan** [ddopson/node-segfault-handler#45]
here is what I get, it doesn't help to find where is the bug.... painfully life...

sometime:
``
PID 8 received SIGSEGV for address: 0x1fc62c0^M
/sptrader_api_server/node_modules/segfault-handler/build/Release/segfault-handler.node(+0x1b60)[0x7f2978c67b60]
/lib/x86_64-linux-gnu/libpthread.so.0(+0x11390)[0x7f297e525390]
node[0x1fc62c0]
pure virtual method called
terminate called without an active exception
```

sometime just:
```
PID 8 received SIGSEGV for address: 0x1fc62c0
/sptrader_api_server/node_modules/segfault-handler/build/Release/segfault-handler.node(+0x1b60)[0x7f0c67dc2b60]
/lib/x86_64-linux-gnu/libpthread.so.0(+0x11390)[0x7f0c6d680390]
node[0x1fc62c0]
```

**Comment by wanjochan** [comment]
this is info came along with the gdb $PROGRAM $CORE_DUMP_FILE

```
#0  0x0000000001fc62c0 in default_loop_struct ()
No symbol table info available.
#1  0x0000000001429bcc in uv__async_event (loop=0x1fc6120 <default_loop_struct>, w=<optimized out>, nevents=<optimized out>) at ../deps/uv/src/unix/async.c:98
        queue = {0x1fc62d0 <default_loop_struct+432>, 0x23b3190}
        q = <optimized out>
        h = <optimized out>
#2  0x0000000001429cc3 in uv__async_io (loop=0x1fc6120 <default_loop_struct>, w=0x1fc62e8 <default_loop_struct+456>, events=<optimized out>) at ../deps/uv/src/unix/async.c:138
        val = <optimized out>
        wa = 0x1fc62e0 <default_loop_struct+448>
        buf = "\001\000\000\000\000\000\000\000\230\324\r(\376\177\000\000\242*\000\000\000\000\000\000\234*\000\000\000\000\000\000\240\310\r(\376\177\000\000\023\266\347\000\002", '\000' <repeats 11 times>, "\360\331\r( _<\002\000\000\000\000\000\000\000\000\000\237\266\251\036%fi\300\310\r(\376\177\000\000 \324\r(\376\177\000\000\350\226I\002\000\000\000\000\220\312\r(\376\177\000\000\200\311\r(\376\177\000\000p\317\r(\376\177\000\000\060\312\r(\376\177\000\000\301\317\343\000\000\000\000\000`\311\r(\376\177\000\000\316t\343\000\000\000\000\000p\311\r(\376\177\000\000\316t\343\000\000\000\000\000\000\000\000\000\376\177\000\000W", '\000' <repeats 11 times>, "\376\177\000\000"...
        n = 8
        __PRETTY_FUNCTION__ = "uv__async_io"
#3  0x000000000143ac08 in uv__io_poll (loop=loop@entry=0x1fc6120 <default_loop_struct>, timeout=3137) at ../deps/uv/src/unix/linux-core.c:382
        no_epoll_pwait = 0
        no_epoll_wait = 0
        events = {{events = 1, data = 8}, {events = 0, data = 0}, {events = 0, data = 2886189023292817408}, {events = 32766, data = 38378048}, {events = 671994160, 
            data = 164841394576326654}, {events = 0, data = 38380128}, {events = 671993488, data = 2886196170118430718}, {events = 32766, data = 139685133711756}, {events = 671993488, 
            data = 2886196170118430718}, {events = 32766, data = 140729570414896}, {events = 14948643, data = 4294967296}, {events = 0, data = 38378048}, {events = 671994160, 
            data = 164841394576326654}, {events = 0, data = 38380128}, {events = 14946782, data = 2886205301218869248}, {events = 32766, data = 140729570415688}, {events = 4294967295, 
            data = 18446744073709551615}, {events = 1, data = 18446744073709551615}, {events = 38368176, data = 46789373722624}, {events = 1, data = 8605120256}, {events = 671993344, 

```
