### ISSUE TITLE
Failing to run on Alpine Linux 

### ISSUE THREAD

**Issue by quentin-sommer** [ddopson/node-segfault-handler#52]
Hi,

I'm trying to use this package on alpine linux using an official node image [node:8-alpine](https://github.com/nodejs/docker-node/blob/e3ec2111af089e31321e76641697e154b3b6a6c3/8/alpine/Dockerfile)

The `npm i` works but when starting the program I get this error:
```
/usr/app/node_modules/bindings/bindings.js:88
        throw e
        ^

Error: Error relocating /usr/app/node_modules/segfault-handler/build/Release/segfault-handler.node: backtrace: symbol not found
    at Object.Module._extensions..node (module.js:681:18)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at bindings (/usr/app/node_modules/bindings/bindings.js:81:44)
    at Object.<anonymous> (/usr/app/node_modules/segfault-handler/index.js:3:37)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
```

I searched a bit and found this issue: https://github.com/nodejs/node-report/issues/86 that seems to deal with a similar problem. I don't have a big understanding of what's going on linux wise here, do you think it could be the same problem?

**Comment by quentin-sommer** [comment]
Closing because I don't work on this anymore

**Comment by pierreinglebert** [comment]
If you ever reuse Alpine or someone is interested, this bug is fixed in this PR : https://github.com/ddopson/node-segfault-handler/pull/67
